#!/bin/bash
jklog debianinstall "network wlan -- vorbereiten"
jkecho "network wlan -- vorbereiten"
	cp network/default.conf /etc/wpa_supplicant
	chmod 600 /etc/wpa_supplicant/default.conf
	mkdir -p /etc/network/muster
	cp network/interfaces*  /etc/network/muster
	#----------------------------------------------------------
	read -p "ssid: " jkssid
	echo -n "pw: "; read -s jkpw
	#----------------------------------------------------------
	jkecho "kontrolle:" ; cat /etc/wpa_supplicant/default.conf
	jksure "wpa_supplicant ok"
	wpa_passphrase $jkssid $jkpw >> /etc/wpa_supplicant/default.conf
	mkdir -p /etc/network/kabel
	cp /etc/network/interfaces /etc/network/kabel/interfaces.dhcp
	cp /etc/network/muster/interfaces.3.wlandhcp /etc/network/interfaces
	modprobe -rf b43
	modprobe  b43
	rfkill
	jksure "ok"
	/etc/init.d/networking restart
	jkping
