#!/bin/bash
Version="0.52  vom 22.3.2020"
# Fehler behoben: In Zeile 16 $2 statt $1
echo "Klaus Junker: $0 --- Version: $Version";
#----------------------------------------------------------------------
if (($#<2));	then 
		echo "Usage: $0 Benutzer Passwort  und optional 4 Bemerkungen"; 
		exit ;
fi
#echo "debug: $1 $2 $3 $4 $5 $6"
Homeverzeichnis="/extern/home/$1"
Gruppe="schueler20"
addgroup $Gruppe
#----------------------------------------------------------------------
adduser --home $Homeverzeichnis --ingroup $Gruppe -gecos "$3,$4,$5,$6" --disabled-password $1 
usermod --password  `perl -e "print crypt($2,'aa');"` $1
#----------------------------------------------------------------------
mysqluser="'$1'@'localhost'"
mysqluser2="'$12nd'@'localhost'"
echo "database=$1" >> $Homeverzeichnis/.my.cnf
echo "[client]" >> $Homeverzeichnis/.my.cnf
echo "user=$1" >> $Homeverzeichnis/.my.cnf
echo "password=$2" >> $Homeverzeichnis/.my.cnf
#echo debug: $mysqluser, $mysqluser2
#----------------------------------------------------------------------
mysql -e "create user $mysqluser   identified by '$2';"
mysql -e "create user $mysqluser2  identified by '$2';"
mysql -e "create database $1;"
mysql -e "create database $12nd;"
mysql -e "grant all on $1.* to $mysqluser;"
mysql -e "grant all on $12nd.* to $mysqluser2;"
#----------------------------------------------------------------------
for i in {1..9..1}
  do 
    mysql -e "create database $1_$i;"
    mysql -e "grant all on $1_$i.* to $mysqluser;"
  done
mysql -e "flush privileges;"
#----------------------------------------------------------------------

