#!/bin/bash
Version="0.5  vom 6.1.2020"
echo "Klaus Junker: $0  --- Version: $Version";
# Klaus Junker 
if (($#<2));	then 
  echo "Usage: $0 Benutzer yes"; 
	exit ;
fi
if [ "$2" = "yes" ];	then 
  echo "delete $1"
  userdel -r $1 
  mysqluser="'$1'@'localhost'"
  mysql -e "drop user if exists $1@localhost;"
  mysql -e "drop user if exists $12nd@localhost;"
  mysql -e "drop database if exists $1;"
  mysql -e "drop database if exists $12nd;"
  for i in {1..9..1}
    do 
      mysql -e "drop database if exists $1_$i;"
    done
  mysql -e "flush privileges;"
else
  echo "$2 sollte yes sein!"
  echo "Usage: $0 Benutzer yes"; 
fi
echo Ende $0 
