#!/bin/bash
#-----------------------------------------------------------------------------
jklog debianinstall "start: $0 --- "
#-----------------------------------------------------------------------------
jkecho "install mc ssh vim"
	jklog debianinstall "-1: mc/ssh/vim"
		aptitude install mc ssh vim -y
jkecho "install mysql"
	jklog debianinstall "-1: mysql "
		aptitude install default-mysql-client default-mysql-server mdbtools -y
#-----------------------------------------------------------------------------
jklog debianinstall "ende:  $0 --- "
#-----------------------------------------------------------------------------
