#!/bin/bash
gelb="\e[1;33m";normal="\e[m"
echo -e "${gelb}install xfce $normal"
jklog debianinstall "start: $0 --- "
aptitude install xfce4 -y
aptitude install xfce4-terminal -y
aptitude install xfce4-goodies -y
jklog debianinstall "ende:  $0 --- "
