#!/bin/bash
gelb="\e[1;33m"
normal="\e[m"
echo -e "$gelb install xfce $normal"
LOG="/var/log/debianinstall.log"
echo -n "-- start: $0 --- " >>$LOG; date >> $LOG
aptitude install xfce4 -y
aptitude install xfce4-terminal -y
aptitude install xfce4-goodies -y
echo -n "--  ende: $0 --- " >>$LOG; date >> $LOG
