#!/bin/bash
#-----------------------------------------------------------------------------
jklog debianinstall "start: $0 --- "
#-----------------------------------------------------------------------------
jkecho "install xfce"
	jklog debianinstall "-1: xfce.. "
		aptitude install xfce4 -y
	jklog debianinstall "-2: xfcei-terminal"
		aptitude install xfce4-terminal -y
	jklog debianinstall "-3: xfce-goodies"
		aptitude install xfce4-goodies -y
#-----------------------------------------------------------------------------
jklog debianinstall "ende:  $0 --- "
#-----------------------------------------------------------------------------


