#!/bin/bash
#-----------------------------------------------------------------------------
jklog debianinstall "start: $0 --- "
#-----------------------------------------------------------------------------
#python
jkecho "install lazarus"
	jklog debianinstall "-91-1: lazarus.. "
		aptitude install lazarus -y
jkecho "install java"
	jklog debianinstall "-91-2: java.."
		aptitude install default-jre default-jdk  -y
#-----------------------------------------------------------------------------
jklog debianinstall "ende:  $0 --- "
#-----------------------------------------------------------------------------
