#!/bin/bash
#-----------------------------------------------------------------------------
jklog debianinstall "start: $0 --- "
#-----------------------------------------------------------------------------
jkecho "install sagemath"
	jklog debianinstall "-1: sagemath"
		aptitude install sagemath -y
jkecho "install tex"
	jklog debianinstall "-1: tex"
		aptitude install texlive texlive-science texlive-lang-german  texlive-bibtex-extra  -y
		aptitude install texlive-fonts-extra  texlive-extra-utils  texlive-games  texlive-metapost  -y
		aptitude install texlive-pstricks texlive-humanities  -y
		aptitude install latexila -y

jkecho "install browser"
	jklog debianinstall "-1: firefox"
		aptitude install firefox-esr firefox-esr-l10n-de -y
	jklog debianinstall "-2: chromium"
		aptitude install chromium chromium-l10n -y
	jklog debianinstall "-3: lynx w3m"
		aptitude install w3m lynx -y

jkecho "install libreoffice"
	jklog debianinstall "-1: libreoffice"
		aptitude install libreoffice-calc libreoffice-writer libreoffice-help-de -y
#pdf
jkecho "install pdf"
	jklog debianinstall "-1: pdf.."
		aptitude install atril evince xpdf zathura -y
#ebook
jkecho "install ebook"
	jklog debianinstall "-1: callibre"
		aptitude install djview calibre -y
#ftp
jkecho "install ftp"
	jklog debianinstall "-1: ftp"
		aptitude install filezilla -y
#medien
jkecho "install media"
	jklog debianinstall "-1: vlc"
		aptitude install vlc -y
#bilder
jkecho "install bilder"
	jklog debianinstall "-1: feh.."
		aptitude install feh fbi -y
#man
jkecho "install manpages"
	jklog debianinstall "-1: man"
		aptitude install man manpages-de less -y
#
jkecho "install emulator"
	jklog debianinstall "-1: playonlinux"
		aptitude install playonlinux -y

#-----------------------------------------------------------------------------
jklog debianinstall "ende:  $0 --- "
#-----------------------------------------------------------------------------
