#!/bin/bash
Version="0.53  vom 22.8.2021"
# mysqluser löschen
clear;
echo "Klaus Junker: $0 --- Version: $Version";
#----------------------------------------------------------------------
if (( $# > 1 )); then echo "$0 - jk - Fehler: max 1  Parameter erlaubt"; exit; fi
if (( $# < 1 )); then  
read -p "name: " jkname
fi
if (( $#  == 1 )); then 
jkname=$1
fi
read -p "delete $jkname ok? [y|Y]: " jksure
read -p "Are you sure?!? [y/N]: " jksure 
case "$jksure" in 
	[yY]) 
				echo "ok";; 
	[nN])	
				echo "dann halt nicht!"
				exit;; 
	*)		
				echo "mach ich nur mit y oder Y!"
#				exit;; 
esac 
 
mysql -e "drop user if exists $jkname";
mysql -e "drop database if exists $jkname";
