#!/bin/bash
sed -i 's/FONTFACE/#FONTFACE/g' /etc/default/console-setup
sed -i 's/FONTSIZE/#FONTSIZE/g' /etc/default/console-setup
echo 'FONTFACE="TerminusBold"' >> /etc/defalut/console-setup
echo 'FONTSIZE="12x24"' >> /etc/defalut/console-setup
echo 'BEEP=OFF' >> /etc/defalut/console-setup
/etc/init.d/console-setup.sh restart
cp skel/.[a-z]* /root
cp skel/.[a-z]* /etc/skel
cp skel/.[a-z]* /home/gast
echo "database=gast" >> /home/gast/.my.cnf
echo "[client]" >> /home/gast/.my.cnf
echo "user=gast" >> /home/gast/.my.cnf
echo "password=gast" >> /home/gast/.my.cnf
chown gast.gast /home/gast/.[a-z]* 
mysql < mysql/createusergast.sql 
