#!/bin/bash
mkdir -p /etc/wpa_supplicant
cp network/default.conf /etc/wpa_supplicant
chmod 600 /etc/wpa_supplicant/default.conf
cp -r network/interfaces/*  /etc/network/
jkecho "kontrolle:" ; cat /etc/wpa_supplicant/default.conf
