#!/bin/bash
jklog debianinstall "network wlan -- vorbereiten"
jkecho "network wlan -- vorbereiten"
	cp network/default.conf /etc/wpa_supplicant
	chmod 600 /etc/wpa_supplicant/default.conf
	mkdir -p /etc/network/muster
	cp network/interfaces*  /etc/network/muster
	#----------------------------------------------------------
	read -p "ssid: " jkssid
	echo -n "pw: "; read -s jkpw
	#----------------------------------------------------------
	jkecho "kontrolle:" ; cat /etc/wpa_supplicant/default.conf
	jksure "wpa_supplicant ok"
	wpa_passphrase $jkssid $jkpw >> /etc/wpa_supplicant/default.conf
	cp /etc/network/alle/interfaces.3.wlandhcp /etc/network/interfaces
	echo "Kontrolle:"; cat /etc/wpa_supplicant/default.conf
	jksure "wpa_supplicant ok"

	echo "testen: rfkill list unblock 0 1 2 "
	rfkill unblock 0
	rfkill unblock 1
	rfkill list
	read -p "press enter: " jkenter
	echo "modprobe -rf b43"
	echo "/etc/init.d/networking restart"
	/etc/init.d/networking restart
	read -p "press enter: " jkenter
	echo "ip link set dev wlan0 up"
	echo "iw dev wlan0 link oder iwconfig"
	iw dev wlan0 link
	read -p "press enter: " jkenter
	iwconfig
	read -p "press enter: " jkenter
	echo "systemctl status networking"
	read -p "press enter: " jkenter
	jkping
	ping -c4 8.8.8.8
